#!/data/data/com.termux/files/usr/bin/php
<?php
// Termux Assistant v1 (beta)
// Author: Bagaz Mukti
// Github: https://github.com/BagazMukti/
$path="/data/data/com.termux/files/usr/bin/";
$nc="\e[0m";
$white="\e[1;37m";
$black="\e[0;30m";
$blue="\e[0;34m";
$light_blue="\e[1;34m";
$green="\e[0;32m";
$light_green="\e[1;32m";
$cyan="\e[0;36m";
$light_cyan="\e[1;36m";
$red="\e[0;31m";
$light_red="\e[1;31m";
$purple="\e[0;35m";
$light_purple="\e[1;35m";
$brown="\e[0;33m";
$yellow="\e[1;33m";
$gray="\e[0;30m";
$light_gray="\e[0;37m";
function home() {
	return print "\e[1;33m   _______                    __
  / /_   _| __ ___  _   ___  _\ \
 | |  | || '_ ` _ \| | | \ \/ /| |
\e[1;36m< <   | || | | | | | |_| |>  <  > >
 | |  |_||_| |_| |_|\__,_/_/\_\| |
  \_\                         /_/ \n\e[0;31m + ++ ++ += Bagaz Mukti =+ ++ ++ +\n\e[0m";
}
home();
while(true) {
	print "\e[0;32m
+ ++ [ MENU ] ++ +
[1] Update list packages
[2] Upgrade all packages
[3] Install packages
[4] Remove packages
[5] Clone repositories on github
[6] Webserver tools
[7] Hacking tools
[8] Text editor
[9] Art tools
[10] About and info
[11] Exit

  \e[1;33mInsert number of the menu.

\e[0;31mtmux> ";
	$menu = fgets(STDIN);
	if($menu == 1) {
		print "++[ Update list packages\n\e[0m";
		passthru($path."apt update");
	} elseif($menu == 2) {
   print "++[ Upgrade all packages\n\e[0m";
		passthru($path."apt upgrade");
	} elseif($menu == 3) {
		print "++[ Install packages\n\nPackage name: ";
		$package = fgets(STDIN);
		print "\e[0m";
		passthru($path."apt install ".$package);
	} elseif($menu == 4) {
		print "++[ Remove packages\nPackage name: ";
		$package = fgets(STDIN);
		print "\e[0m";
		passthru($path."apt remove ".$package);
	} elseif($menu == 5) {
		print "++[ Clone repositories on github\n";
		if(stristr(shell_exec('git'), 'usage')) {
			print "Url repository: ";
			$url = fgets(STDIN);
			print "\e[0m";
			passthru($path."git clone ".$url);
		} else {
			print "Error: 'git' not installed\n";
		}
	} elseif($menu == 6) {
		print "++[ Webserver tools
[1] Install webserver(nginx)
[2] Edit configuration
[3] Run webserver
choose> ";
		$choose = fgets(STDIN);
		print "\e[0m";
		if($choose == 1) {
			passthru($path."apt install nginx");
		} elseif($choose == 2) {
			passthru($path."vim /data/data/com.termux/files/usr/etc/nginx/nginx.conf");
		} elseif($choose == 3) {
			passthru($path."nginx");
		} else {
			print "\e[0;31mError: Invalid input\n";
		}
	} elseif($menu == 7) {
		print "++[ Hacking tools
[1] sqlmap
[2] Weevely
[3] Hydra
choose> ";
		$choose = fgets(STDIN);
		print "\e[0m";
		if($choose == 1) {
			passthru($path."git clone https://github.com/sqlmapproject/sqlmap/");
		} elseif($choose == 2) {
			passthru($path."git clone https://github.com/glides/Weevely");
		} elseif($choose == 3) {
			passthru($path."apt install hydra");
		} else {
			print "\e[0;31mError: Invalid input";
		}
	} elseif($menu == 8) {
		print "++[ Text Editor
[1] Install vim
[2] Install nano
choose> ";
		$choose = fgets(STDIN);
		print "\e[0m";
		if($choose == 1) {
			passthru($path."apt install vim");
		} elseif($choose == 2) {
			passthru($path."apt install nano");
		} else {
 			print "\e[0;31mError: Invalid input\n";
		}
	} elseif($menu == 9) {
		print "++[ Art tools
[1] figlet
[2] CowSay
choose> ";
		$choose = fgets(STDIN);
		print "\e[0m";
		if($choose == 1) {
			passthru($path."apt install figlet");
		} elseif($choose == 2) {
			passthru($path."apt install cowsay");
		} else {
			print "\e[0;31mError: Invalid input\n";
		}
	} elseif($menu == 10) {
		print "++[ About
Termux Assistant V1
[ \e[0;32mhttps://github.com/BagazMukti/Terass/\e[0;31m ]
Author: Bagaz Mukti
Contact: bgz@null.net
Exit(y/n) ?> ";
		$choose = fgets(STDIN);
		if($choose == 'y
') {
			print "\n\e[0mGood bye\n\n";
			exit();
		} else {
			true;
		}
	} elseif($menu == 11) {
		print "++[ Exit\n\n\e[0mGood bye\n\n";
		exit();
	} else {
		print "Error: Invalid menu\n";
	}
}